// Mappings from GTA API documentation

export const GTA_EVALUATION: Record<number, string> = {
  1: "Red",
  2: "Amber",
  3: "Green",
  4: "Harmful",
  5: "Liberalising",
};

export const AFFECTED_FLOW: Record<number, string> = {
  1: "Inward",
  2: "Outward",
  3: "Outward subsidy",
};

export const IMPLEMENTATION_LEVEL: Record<number, string> = {
  1: "Supranational",
  2: "National",
  3: "Subnational",
  4: "SEZ",
  5: "IFI",
  6: "NFI",
};

export const ELIGIBLE_FIRM: Record<number, string> = {
  1: "all",
  2: "SMEs",
  3: "firm-specific",
  4: "state-controlled",
  5: "state trading enterprise",
  6: "sector-specific",
  7: "location-specific",
  8: "processing trade",
};

export const MAST_CHAPTER: Record<number, string> = {
  1: "A: Sanitary and phytosanitary measure",
  2: "B: Technical barriers to trade",
  3: "Capital control measures",
  4: "D: Contingent trade-protective measures",
  5: "E: Non-automatic licensing, quotas etc.",
  6: "F: Price-control measures",
  7: "FDI measures",
  8: "G: Finance measures",
  9: "I: Trade-related investment measures",
  10: "L: Subsidies",
  11: "M: Government procurement restrictions",
  12: "Migration measures",
  13: "N: Intellectual Property",
  14: "P: Export-related measures",
  15: "Tariff measures",
  16: "Instrument unclear",
  17: "C: Pre-shipment inspection",
};

export const INTERVENTION_TYPE: Record<number, string> = {
  1: "Capital injection and equity stakes",
  2: "State loan",
  3: "Financial grant",
  4: "In-kind grant",
  5: "Production subsidy",
  6: "Interest payment subsidy",
  7: "Loan guarantee",
  8: "Tax or social insurance relief",
  9: "Competitive devaluation",
  10: "Repatriation & surrender requirements",
  11: "Controls on commercial transactions",
  12: "Controls on credit operations",
  13: "Control on personal transactions",
  14: "Consumption subsidy",
  15: "Tax-based export incentive",
  16: "Export subsidy",
  17: "Other export incentive",
  18: "Export tax",
  19: "Export ban",
  20: "Export tariff quota",
  21: "Export quota",
  22: "Import ban",
  23: "Import incentive",
  24: "Intellectual property protection",
  25: "FDI: Entry and ownership rule",
  26: "FDI: Treatment and operations",
  27: "FDI: Financial incentive",
  28: "Local content requirement",
  29: "Local operations requirement",
  30: "Local labour requirement",
  31: "Labour market access",
  32: "Post-migration treatment",
  33: "Trade payment measure",
  34: "Trade balancing measure",
  35: "Export licensing requirement",
  36: "Import licensing requirement",
  37: "Export-related non-tariff measure",
  38: "Import-related non-tariff measure",
  39: "Foreign customer limit",
  40: "Public procurement preference margin",
  41: "Public procurement localisation",
  42: "Public procurement access",
  43: "Public procurement, nes",
  44: "Import tariff quota",
  45: "Import quota",
  46: "Sanitary and phytosanitary measure",
  47: "Import tariff",
  48: "Internal taxation of imports",
  49: "Technical barrier to trade",
  50: "Import monitoring",
  51: "Anti-dumping",
  52: "Safeguard",
  53: "Anti-subsidy",
  54: "Trade finance",
  55: "Financial assistance in foreign market",
  56: "Anti-circumvention",
  57: "Local content incentive",
  58: "Special safeguard",
  59: "State aid, nes",
  60: "Instrument unclear",
  61: "Price stabilisation",
  62: "State aid, unspecified",
  63: "Local supply requirement for exports",
  64: "Local value added requirement",
  65: "Local value added incentive",
  66: "Local operations incentive",
  67: "Local labour incentive",
  68: "Localisation, nes",
  69: "Voluntary export-restraint arrangements",
  70: "Voluntary export-price restraints",
  71: "Minimum import price",
  72: "Import price benchmark",
  73: "Other import charges",
  74: "Export price benchmark",
};

// Key jurisdictions (subset for common filters)
export const JURISDICTIONS: Record<number, string> = {
  840: "United States",
  156: "China",
  276: "Germany",
  251: "France",
  826: "United Kingdom",
  381: "Italy",
  724: "Spain",
  392: "Japan",
  410: "South Korea",
  356: "India",
  864: "Brazil",
  124: "Canada",
  36: "Australia",
  752: "Sweden",
  578: "Norway",
  246: "Finland",
  208: "Denmark",
  528: "Netherlands",
  756: "Switzerland",
  682: "Saudi Arabia",
  634: "Qatar",
  784: "United Arab Emirates",
  414: "Kuwait",
  516: "Namibia",
  710: "South Africa",
};
